//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatisserieCestBon.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された顧客IDまたはパスワードが誤っています。")]
        public string p001_error_Auth {
            get {
                return ((string)(this["p001_error_Auth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客ID（パスワード）が入力されていません。")]
        public string p001_error_Recuired {
            get {
                return ((string)(this["p001_error_Recuired"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("電話番号は「xxxx-yyyy-zzzz」の形式で入力してください。")]
        public string p002_error_FormatTelNo {
            get {
                return ((string)(this["p002_error_FormatTelNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メールアドレスは「xxxx@yyyy」の形式で入力してください。")]
        public string p002_error_FormatEmail {
            get {
                return ((string)(this["p002_error_FormatEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客担当者名かなは、 全角ひらがなで入力してください。")]
        public string p002_error_CharTypeKana {
            get {
                return ((string)(this["p002_error_CharTypeKana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メールアドレスは、半角英数字と記号で入力してください。")]
        public string p002_error_CharTypeEmail {
            get {
                return ((string)(this["p002_error_CharTypeEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("電話番号は、半角数字と半角ハイフンで入力してください。")]
        public string p002_error_CharTypeTelNo {
            get {
                return ((string)(this["p002_error_CharTypeTelNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("会社名を入力してください。")]
        public string p002_error_RecuiredCompanyName {
            get {
                return ((string)(this["p002_error_RecuiredCompanyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("住所を入力してください。\r\n")]
        public string p002_error_RecuiredAddress {
            get {
                return ((string)(this["p002_error_RecuiredAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("電話番号を入力してください。\r\n")]
        public string p002_error_RecuiredTelNo {
            get {
                return ((string)(this["p002_error_RecuiredTelNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("氏名（漢字）を入力してください。\r\n")]
        public string p002_error_RecuiredCustomerName {
            get {
                return ((string)(this["p002_error_RecuiredCustomerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("氏名（かな）を入力してください。\r\n")]
        public string p002_error_RecuiredCustomerKana {
            get {
                return ((string)(this["p002_error_RecuiredCustomerKana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードを入力してください。\r\n")]
        public string p002_error_RecuiredPassword {
            get {
                return ((string)(this["p002_error_RecuiredPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("確認用パスワードを入力してください。\r\n")]
        public string p002_error_RequiredRetypePassword {
            get {
                return ((string)(this["p002_error_RequiredRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードが確認用パスワードと一致しません。\r\n")]
        public string p002_error_MatchRetypePassword {
            get {
                return ((string)(this["p002_error_MatchRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量は0より大きい値を入力してください。\r\n")]
        public string p007_error_ZeroQuantity {
            get {
                return ((string)(this["p007_error_ZeroQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在庫数量より多い数量を指定することはできません。\r\n")]
        public string p007_error_AppropriateQuantity {
            get {
                return ((string)(this["p007_error_AppropriateQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正しい希望納期を入力してください。\r\n")]
        public string p007_error_AppropriateDeliveryDate {
            get {
                return ((string)(this["p007_error_AppropriateDeliveryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量は整数で入力してください。\r\n")]
        public string p007_error_FormatQuantity {
            get {
                return ((string)(this["p007_error_FormatQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("希望納期は「yyyy/mm/dd」の形式で入力してください。\r\n")]
        public string p007_error_FormatDeliveryDate {
            get {
                return ((string)(this["p007_error_FormatDeliveryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量（納期）を入力してください。\r\n")]
        public string p007_error_Recuired {
            get {
                return ((string)(this["p007_error_Recuired"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量（納期）を入力してください。\r\n")]
        public string p009_error_Recuired {
            get {
                return ((string)(this["p009_error_Recuired"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量は整数で入力してください。\r\n")]
        public string p009_error_FormatQuantity {
            get {
                return ((string)(this["p009_error_FormatQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("希望納期は「yyyy/mm/dd」の形式で入力してください。\r\n")]
        public string p009_error_FormatDeliveryDate {
            get {
                return ((string)(this["p009_error_FormatDeliveryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量は0より大きい値を入力してください。\r\n")]
        public string p009_error_ZeroQuantity {
            get {
                return ((string)(this["p009_error_ZeroQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量・納期を変更した場合は、再見積を実行してから注文ボタンを押してください。\r\n")]
        public string p009_error_CartReCheck {
            get {
                return ((string)(this["p009_error_CartReCheck"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("正しい希望納期を入力してください。\r\n")]
        public string p009_error_AppropriateDeliveryDate {
            get {
                return ((string)(this["p009_error_AppropriateDeliveryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在庫が不足するため、ご注文を確定できません。\r\n")]
        public string p009_error_AppropriateQuantity {
            get {
                return ((string)(this["p009_error_AppropriateQuantity"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("出荷済の在庫があるため、このご注文はキャンセルできません。\r\n")]
        public string p011_error_CannotCancel {
            get {
                return ((string)(this["p011_error_CannotCancel"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された社員番号またはパスワードが誤っています。")]
        public string p013_error_Auth {
            get {
                return ((string)(this["p013_error_Auth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("社員番号（パスワード）が入力されていません。\r\n")]
        public string p013_error_Recuired {
            get {
                return ((string)(this["p013_error_Recuired"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された条件に適合する受注情報は存在しません。\r\n")]
        public string p015_error_NoMatch {
            get {
                return ((string)(this["p015_error_NoMatch"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客IDは数値で入力してください。\r\n")]
        public string p015_error_FormatCustomerId {
            get {
                return ((string)(this["p015_error_FormatCustomerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注文番号は数値で入力してください。\r\n")]
        public string p015_error_FormatOrderNo {
            get {
                return ((string)(this["p015_error_FormatOrderNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客IDは6桁以内で入力してください。\r\n")]
        public string p015_error_LengthCustomerId {
            get {
                return ((string)(this["p015_error_LengthCustomerId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("注文番号は6桁以内で入力してください。\r\n")]
        public string p015_error_LengthOrderNo {
            get {
                return ((string)(this["p015_error_LengthOrderNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("納期（受注日時）のFrom・Toは「yyyy/mm/dd」の形式で入力してください。\r\n")]
        public string p015_error_FormatDate {
            get {
                return ((string)(this["p015_error_FormatDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("納期（From）は、納期（To）と同じか、それよりも前の日付を指定してください。\r\n")]
        public string p015_error_AppropriateDeliveryDate {
            get {
                return ((string)(this["p015_error_AppropriateDeliveryDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("受注日時（From）は、受注日時（To）と同じか、それよりも前の日付を指定してください。\r\n")]
        public string p015_error_AppropriateOrderDate {
            get {
                return ((string)(this["p015_error_AppropriateOrderDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在庫数量が不足しています。\r\n")]
        public string p017_error_ShortageStock {
            get {
                return ((string)(this["p017_error_ShortageStock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在庫情報を更新しました。\r\n")]
        public string p019_info_UpdateSuccess {
            get {
                return ((string)(this["p019_info_UpdateSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在庫数量の減少に失敗しました。\r\n")]
        public string p020_error_StockAlreadyZero {
            get {
                return ((string)(this["p020_error_StockAlreadyZero"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("在庫が不足するため減少できません。\r\n")]
        public string p020_error_UpdateStock {
            get {
                return ((string)(this["p020_error_UpdateStock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("数量には数値を入力してください。\r\n")]
        public string p020_error_CharTypeStock {
            get {
                return ((string)(this["p020_error_CharTypeStock"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入荷予定日は「yyyy/mm/dd」形式で入力してください。\r\n")]
        public string p020_error_FormatReceiptDate {
            get {
                return ((string)(this["p020_error_FormatReceiptDate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("担当者情報を登録しました。\r\n")]
        public string p021_info_AddSuccess {
            get {
                return ((string)(this["p021_info_AddSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("担当者情報を更新しました。\r\n")]
        public string p021_info_UpdateSuccess {
            get {
                return ((string)(this["p021_info_UpdateSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("担当者情報を削除しました。\r\n")]
        public string p021_info_DeleteSuccess {
            get {
                return ((string)(this["p021_info_DeleteSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("該当の担当者情報はすでに削除されています。\r\n")]
        public string p021_error_AlreadyDeletedEmployee {
            get {
                return ((string)(this["p021_error_AlreadyDeletedEmployee"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("削除を行う場合は、削除したい担当者を選択してください。\r\n")]
        public string p021_error_NotChecked {
            get {
                return ((string)(this["p021_error_NotChecked"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された社員番号はすでに登録されています。\r\n")]
        public string p022_error_DuplicatedEmployeeId {
            get {
                return ((string)(this["p022_error_DuplicatedEmployeeId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードが確認用パスワードと一致しません。\r\n")]
        public string p022_error_MatchRetypePassword {
            get {
                return ((string)(this["p022_error_MatchRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("確認用パスワードを入力してください。\r\n")]
        public string p022_error_RecuiredRetypePassword {
            get {
                return ((string)(this["p022_error_RecuiredRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("社員番号は1000から始まる4桁の数値で入力してください。\r\n")]
        public string p022_error_FormatEmployeeId {
            get {
                return ((string)(this["p022_error_FormatEmployeeId"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードは半角英数字と記号のみで入力してください。\r\n")]
        public string p022_error_CharTypePassword {
            get {
                return ((string)(this["p022_error_CharTypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("社員番号を入力してください。\r\n")]
        public string p022_error_RecuiredEmpNo {
            get {
                return ((string)(this["p022_error_RecuiredEmpNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("担当者氏名を入力してください。\r\n")]
        public string p022_error_RecuiredEmpName {
            get {
                return ((string)(this["p022_error_RecuiredEmpName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードを入力してください。\r\n")]
        public string p022_error_RecuiredPassword {
            get {
                return ((string)(this["p022_error_RecuiredPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("担当者氏名を入力してください。\r\n")]
        public string p024_error_RecuiredEmpName {
            get {
                return ((string)(this["p024_error_RecuiredEmpName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードを入力してください。\r\n")]
        public string p024_error_RecuiredPassword {
            get {
                return ((string)(this["p024_error_RecuiredPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードが確認用パスワードと一致しません。\r\n")]
        public string p024_error_MatchRetypePassword {
            get {
                return ((string)(this["p024_error_MatchRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("確認用パスワードを入力してください。\r\n")]
        public string p024_error_RequiredRetypePassword {
            get {
                return ((string)(this["p024_error_RequiredRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードは半角英数字と記号のみで入力してください。\r\n")]
        public string p024_error_CharTypePassword {
            get {
                return ((string)(this["p024_error_CharTypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客情報を更新しました。\r\n")]
        public string p027_info_UpdateSuccess {
            get {
                return ((string)(this["p027_info_UpdateSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客情報を削除しました。\r\n")]
        public string p027_info_DeleteSuccess {
            get {
                return ((string)(this["p027_info_DeleteSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("該当の顧客情報はすでに削除されています。\r\n")]
        public string p027_error_AlreadyDeletedCustomer {
            get {
                return ((string)(this["p027_error_AlreadyDeletedCustomer"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された情報が不正です。\r\n")]
        public string p028_error_Inappropriate {
            get {
                return ((string)(this["p028_error_Inappropriate"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("電話番号は「xxxx-yyyy-zzzz」の形式で入力してください。\r\n")]
        public string p028_error_FormatTelNo {
            get {
                return ((string)(this["p028_error_FormatTelNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メールアドレスは「xxxx@yyyy」の形式で入力してください。\r\n")]
        public string p028_error_FormatEmail {
            get {
                return ((string)(this["p028_error_FormatEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("顧客担当者名かなは、 全角ひらがなで入力してください。\r\n")]
        public string p028_error_CharTypeKana {
            get {
                return ((string)(this["p028_error_CharTypeKana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("メールアドレスは、半角英数字と記号で入力してください。\r\n")]
        public string p028_error_CharTypeEmail {
            get {
                return ((string)(this["p028_error_CharTypeEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("電話番号は、半角数字と半角ハイフンで入力してください。\r\n")]
        public string p028_error_CharTypeTelNo {
            get {
                return ((string)(this["p028_error_CharTypeTelNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("会社名を入力してください。\r\n")]
        public string p028_error_RecuiredCompanyName {
            get {
                return ((string)(this["p028_error_RecuiredCompanyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("住所を入力してください。\r\n")]
        public string p028_error_RecuiredAddress {
            get {
                return ((string)(this["p028_error_RecuiredAddress"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("電話番号を入力してください。\r\n")]
        public string p028_error_RecuiredTelNo {
            get {
                return ((string)(this["p028_error_RecuiredTelNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("氏名（漢字）を入力してください。\r\n")]
        public string p028_error_RecuiredCustomerName {
            get {
                return ((string)(this["p028_error_RecuiredCustomerName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("氏名（かな）を入力してください。\r\n")]
        public string p028_error_RecuiredCustomerKana {
            get {
                return ((string)(this["p028_error_RecuiredCustomerKana"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードを入力してください。\r\n")]
        public string p028_error_RecuiredPassword {
            get {
                return ((string)(this["p028_error_RecuiredPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("確認用パスワードを入力してください。\r\n")]
        public string p028_error_RequiredRetypePassword {
            get {
                return ((string)(this["p028_error_RequiredRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("パスワードが確認用パスワードと一致しません。\r\n")]
        public string p028_error_MatchRetypePassword {
            get {
                return ((string)(this["p028_error_MatchRetypePassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品情報を登録しました。\r\n")]
        public string p031_info_AddSuccess {
            get {
                return ((string)(this["p031_info_AddSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品情報を更新しました。\r\n")]
        public string p031_info_UpdateSuccess {
            get {
                return ((string)(this["p031_info_UpdateSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品情報を削除しました。\r\n")]
        public string p031_info_DeleteSuccess {
            get {
                return ((string)(this["p031_info_DeleteSuccess"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("その商品は削除できません。\r\n")]
        public string p031_error_ThereIsStockOrOrder {
            get {
                return ((string)(this["p031_error_ThereIsStockOrOrder"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("該当商品情報はすでに削除されています。\r\n")]
        public string p031_error_AlreadyDeletedItem {
            get {
                return ((string)(this["p031_error_AlreadyDeletedItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("削除を行う場合は、削除したい商品を選択してください。\r\n")]
        public string p031_error_NotChecked {
            get {
                return ((string)(this["p031_error_NotChecked"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された商品番号または商品名はすでに登録されています。\r\n")]
        public string p032_error_DupulicatedItem {
            get {
                return ((string)(this["p032_error_DupulicatedItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品番号は4桁の整数で入力してください。\r\n")]
        public string p032_error_FormatItemNo {
            get {
                return ((string)(this["p032_error_FormatItemNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("単価は整数で入力してください。\r\n")]
        public string p032_error_FormatUnitPrice {
            get {
                return ((string)(this["p032_error_FormatUnitPrice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("寸法は「〇〇x〇〇」の形式で入力してください。\r\n")]
        public string p032_error_FormatSize {
            get {
                return ((string)(this["p032_error_FormatSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品番号を入力してください。\r\n")]
        public string p032_error_RecuiredItemNo {
            get {
                return ((string)(this["p032_error_RecuiredItemNo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品名を入力してください。\r\n")]
        public string p032_error_RecuiredItemName {
            get {
                return ((string)(this["p032_error_RecuiredItemName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品画像（URL）を入力してください。\r\n")]
        public string p032_error_RecuiredPhotoUrl {
            get {
                return ((string)(this["p032_error_RecuiredPhotoUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("単価を入力してください。\r\n")]
        public string p032_error_RecuiredUnitPrice {
            get {
                return ((string)(this["p032_error_RecuiredUnitPrice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("寸法を入力してください。\r\n")]
        public string p032_error_RecuiredSize {
            get {
                return ((string)(this["p032_error_RecuiredSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品名を入力してください。\r\n")]
        public string p034_error_RecuiredItemName {
            get {
                return ((string)(this["p034_error_RecuiredItemName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品画像（URL）を入力してください。\r\n")]
        public string p034_error_RecuiredPhotoUrl {
            get {
                return ((string)(this["p034_error_RecuiredPhotoUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("単価を入力してください。\r\n")]
        public string p034_error_RecuiredUnitPrice {
            get {
                return ((string)(this["p034_error_RecuiredUnitPrice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("寸法を入力してください。\r\n")]
        public string p034_error_RecuiredSize {
            get {
                return ((string)(this["p034_error_RecuiredSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("入力された商品名はすでに登録されています。\r\n")]
        public string p034_error_DupulicatedItem {
            get {
                return ((string)(this["p034_error_DupulicatedItem"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("単価は整数で入力してください。\r\n")]
        public string p034_error_FormatUnitPrice {
            get {
                return ((string)(this["p034_error_FormatUnitPrice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("寸法は「〇〇x〇〇」の形式で入力してください。\r\n")]
        public string p034_error_FormatSize {
            get {
                return ((string)(this["p034_error_FormatSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品を削除する場合は、再見積を実行してから注文ボタンを押してください。")]
        public string p009_error_CartReCheckDelete {
            get {
                return ((string)(this["p009_error_CartReCheckDelete"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("商品画像（URL）はURLの形式で入力してください。\r\n")]
        public string p032_error_FormatPhotoUrl {
            get {
                return ((string)(this["p032_error_FormatPhotoUrl"]));
            }
        }
    }
}
