//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PatisserieCestBon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public decimal customerId { get; set; }
        public string companyName { get; set; }
        public string address { get; set; }
        public string telNo { get; set; }
        public string customerName { get; set; }
        public string customerKana { get; set; }
        public string dept { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    }
}
